language: generic

cache:
    directories:
        - $HOME/dotfiles/.repo
        - $HOME/.vim/plugged

os:
    - osx
    - linux

script:
    - mkdir -p ~/dotfiles && cd $HOME/dotfiles
    - git init
    - git remote add origin PATH/TO/REPO
    - git fetch
    - git reset origin/master
    - git checkout -t origin/master
    - ./install.sh
