language: generic
sudo: required

os:
    - osx
    - linux

script:
    - git clone --bare https://github.com/Gnnng/dotfiles $HOME/.dotfiles
    - |
      cat << EOF > $HOME/.dotfiles/info/sparse-checkout
      .*
      !.travis.yml
      EOF
    - |
      shopt -s expand_aliases
      alias dotfiles='git --git-dir $HOME/.dotfiles --work-tree=$HOME'
      dotfiles config --local core.sparseCheckout true
      dotfiles config --local status.showUntrackedFiles no
      dotfiles checkout ${TRAVIS_COMMIT}
      dotfiles status

# matrix:
  # allow_failures:
    # - os: osx
