language: generic
sudo: required

os:
    - osx
    - linux

script:
    - cp -f sparse-checkout .git/info/sparse-checkout
    - git config --local core.sparseCheckout true
    - git config --local status.showUntrackedFiles no
    - git --git-dir $PWD/.git --work-tree=$HOME checkout master
    - ls -al $HOME/

matrix:
  allow_failures:
    - os: osx
