abbr -a gco         'git checkout'
abbr -a gst         'git status'
abbr -a gd          'git diff'
abbr -a gdca        'git diff --cached'
abbr -a ga          'git add'
abbr -a gau         'git add -u'
abbr -a gc          'git commit -v'
abbr -a gc!         'git commit -v --amend'
abbr -a gl          'git pull'
abbr -a gup         'git pull --rebase'
abbr -a grbi        'git rebase -i'
abbr -a grbc        'git rebase --continue'
abbr -a grba        'git rebase --abort'
abbr -a gpsup       'git push --set-upstream origin (git symbolic-ref --short HEAD)'
abbr -a gclean      'git clean -fd'
abbr -a gpristine   'git reset --hard; and git clean -dfx'
abbr -a glo         'git log --oneline'
abbr -a glg         'git log --stat'
abbr -a glgg        'git log --graph'
abbr -a glgga       'git log --graph --decorate --all'
abbr -a glgm        'git log --graph --max-count=10'
abbr -a glgp        'git log --stat -p'
abbr -a glo         'git log --oneline --decorate'
abbr -a glog        'git log --oneline --decorate --graph'
abbr -a gloga       'git log --oneline --decorate --graph --all'
abbr -a glol        'git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'
abbr -a glola       'git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --all'

[ -f ~/.zshrc_local ]; and bass source ~/.zshrc_local
